# contents
nav:
  - Home:
      - インデックス: index.md
      - ほげ: hoge.md

# metadata
site_name: ISDL ARCHIVE Document
theme:
    logo: images/logo.png
        
    name: material
    # サイトの言語設定
    language: ja
    features:
        # トップに戻るボタン
        - navigation.top
docs_dir: src
use_directory_urls: false

  

markdown_extensions:
    - admonition